
	:: Internet Components
call :RemoveWindowsComponent "%InstallMount%", "Adobe Flash For Windows", "AdobeFlashForWindows"
call :RemoveWindowsComponent "%InstallMount%", "Edge Chromium Browser", "EdgeChromium"
call :RemoveWindowsComponent "%InstallMount%", "Internet Explorer", "InternetExplorer"

	:: Multimedia Components
@REM call :RemoveWindowsComponent "%InstallMount%", "First Logon Animation", "FirstLogonAnimation"
call :RemoveWindowsComponent "%InstallMount%", "Game Explorer", "GameExplorer"
@REM call :RemoveWindowsComponent "%InstallMount%", "Snipping Tool", "SnippingTool"
call :RemoveWindowsComponent "%InstallMount%", "Speech Recognition", "SpeechRecognition"
call :RemoveWindowsComponent "%InstallMount%", "Windows Media Player", "WindowsMediaPlayer"
@REM call :RemoveWindowsComponent "%InstallMount%", "Windows Photo Viewer", "WindowsPhotoViewer"
call :RemoveWindowsComponent "%InstallMount%", "Windows System Assessment Tool", "WinSAT"

	:: Privacy Components
@REM call :RemoveWindowsComponent "%InstallMount%", "Assigned Access", "AssignedAccess"
call :RemoveWindowsComponent "%InstallMount%", "Customer Experience Improvement Program [CEIP]", "CEIP_SQM"
@REM call :RemoveWindowsComponent "%InstallMount%", "Face Recognition", "FaceRecognition"
@REM call :RemoveWindowsComponent "%InstallMount%", "Kernel Debugging", "KernelDebugging"
@REM call :RemoveWindowsComponent "%InstallMount%", "Location Service", "LocationService"
@REM call :RemoveWindowsComponent "%InstallMount%", "Picture Password", "PicturePassword"
@REM call :RemoveWindowsComponent "%InstallMount%", "Pin Enrollment", "PinEnrollment"
call :RemoveWindowsComponent "%InstallMount%", "Unified Telemetry Client [Asimov]", "UnifiedTelemetryClient"
@REM call :RemoveWindowsComponent "%InstallMount%", "WiFi Network Manager", "WiFiNetworkManager"
@REM call :RemoveWindowsComponent "%InstallMount%", "Windows Error Reporting", "WindowsErrorReporting"
call :RemoveWindowsComponent "%InstallMount%", "Windows Insider Hub", "WindowsInsiderHub"

	:: Remoting Components
call :RemoveWindowsComponent "%InstallMount%", "HomeGroup", "HomeGroup"
call :RemoveWindowsComponent "%InstallMount%", "MultiPoint Connector", "MultiPointConnector"
call :RemoveWindowsComponent "%InstallMount%", "Remote Assistance", "RemoteAssistance"

	:: System Components
@REM call :RemoveWindowsComponent "%InstallMount%", "Device Lockdown [Embedded Experience]", "DeviceLockdown"
@REM call :RemoveWindowsComponent "%InstallMount%", "Ease Of Access Themes", "EaseOfAccessThemes"
call :RemoveWindowsComponent "%InstallMount%", "Easy Transfer", "EasyTransfer"
call :RemoveWindowsComponent "%InstallMount%", "File History", "FileHistory"
call :RemoveWindowsManualSetup
@REM call :RemoveWindowsComponent "%InstallMount%", "Microsoft Paint", "Paint"
@REM call :RemoveWindowsComponent "%InstallMount%", "Security Center", "SecurityCenter"
call :RemoveWindowsComponent "%InstallMount%", "Steps Recorder", "StepsRecorder"
@REM call :RemoveWindowsComponent "%InstallMount%", "System Restore", "SystemRestore"
@REM call :RemoveWindowsComponent "%InstallMount%", "Windows Backup", "WindowsBackup"
@REM call :RemoveWindowsComponent "%InstallMount%", "Windows Firewall", "WindowsFirewall"
call :RemoveWindowsComponent "%InstallMount%", "Windows Subsystem For Linux", "WindowsSubsystemForLinux"
call :RemoveWindowsComponent "%InstallMount%", "Windows To Go", "WindowsToGo"
call :RemoveWindowsComponent "%InstallMount%", "Wordpad", "Wordpad"

	:: System Apps
@REM call :RemoveWindowsComponent "%InstallMount%", "Azure Active Directory AppX Broker Plugin", "AADBrokerPlugin"
@REM call :RemoveWindowsComponent "%InstallMount%", "Assigned Access Lock App", "AssignedAccessLockApp"
@REM call :RemoveWindowsComponent "%InstallMount%", "Bio Enrollment App", "BioEnrollment"
call :RemoveWindowsComponent "%InstallMount%", "Calling Shell App", "CallingShellApp"
call :RemoveWindowsComponent "%InstallMount%", "Camera Barcode Scanner", "CBSPreview"
call :RemoveWindowsComponent "%InstallMount%", "Content Delivery Manager", "ContentDeliveryManager"
@REM call :RemoveWindowsComponent "%InstallMount%", "Cortana, StartMenu and Settings Search App", "Cortana"
call :RemoveWindowsComponent "%InstallMount%", "Eye Control App", "ECApp"

call :RemoveWindowsComponent "%InstallMount%", "Edge Developer Tools Client", "EdgeDevToolsClient"
call :RemoveWindowsComponent "%InstallMount%", "Edge Browser App", "Edge"
call :RemoveWindowsComponent "%InstallMount%", "Windows Reader [PDF]", "WindowsReaderPDF"

call :RemoveWindowsComponent "%InstallMount%", "Edge Developer Tools Client", "EdgeDevToolsClient"
@REM call :RemoveWindowsComponent "%InstallMount%", "File Explorer App", "FileExplorer"
@REM call :RemoveWindowsComponent "%InstallMount%", "Lockscreen App", "LockApp"
call :RemoveWindowsComponent "%InstallMount%", "Map Control", "MapControl"
call :RemoveWindowsComponent "%InstallMount%", "Narrator QuickStart", "NarratorQuickStart"
call :RemoveWindowsComponent "%InstallMount%", "OneDrive Desktop Client", "OneDrive"
@REM call :RemoveWindowsComponent "%InstallMount%", "Parental Controls App", "ParentalControls"
call :RemoveWindowsComponent "%InstallMount%", "People Experience Host", "PeopleExperienceHost"
call :RemoveWindowsComponent "%InstallMount%", "Connect App", "PPIProjection"
call :RemoveWindowsComponent "%InstallMount%", "Quick Assist App", "QuickAssist"
call :RemoveWindowsComponent "%InstallMount%", "Retail Demo Content", "RetailDemoContent"
call :RemoveWindowsComponent "%InstallMount%", "Take Test App", "SecureAssessmentBrowser"
@REM call :RemoveWindowsComponent "%InstallMount%", "Setting Sync", "SettingSync"
call :RemoveWindowsComponent "%InstallMount%", "Skype ORTC", "SkypeORTC"
call :RemoveWindowsComponent "%InstallMount%", "SmartScreen App", "SmartScreen"
call :RemoveWindowsComponent "%InstallMount%", "Win32 WebView Host", "Win32WebViewHost"
@REM call :RemoveWindowsComponent "%InstallMount%", "Windows Defender App", "WindowsDefender"
call :RemoveWindowsComponent "%InstallMount%", "Windows Mixed Reality", "WindowsMixedReality"
call :RemoveWindowsComponent "%InstallMount%", "Windows Reader [PDF]", "WindowsReaderPDF"
call :RemoveWindowsComponent "%InstallMount%", "Xbox Game Callable UI", "XboxGameCallableUI"

	:: Windows Apps
call :RemoveWindowsComponent "%InstallMount%", "Mixed Reality Viewer App", "3DViewer"
call :RemoveWindowsComponent "%InstallMount%", "Advertising Xaml", "AdvertisingXaml"
call :RemoveWindowsComponent "%InstallMount%", "Alarms and Clock App", "Alarms"
call :RemoveWindowsComponent "%InstallMount%", "Weather App", "BingWeather"
call :RemoveWindowsComponent "%InstallMount%", "Calculator App", "Calculator"
call :RemoveWindowsComponent "%InstallMount%", "Camera App", "Camera"
call :RemoveWindowsComponent "%InstallMount%", "Windows Mail App", "CommunicationsApps"
call :RemoveWindowsComponent "%InstallMount%", "Cortana App", "Cortana"
call :RemoveWindowsComponent "%InstallMount%", "Desktop App Installer", "DesktopAppInstaller"
call :RemoveWindowsComponent "%InstallMount%", "Feedback Hub App", "FeedbackHub"
call :RemoveWindowsComponent "%InstallMount%", "Get Help App", "GetHelp"
call :RemoveWindowsComponent "%InstallMount%", "Tips App", "Getstarted"
call :RemoveWindowsComponent "%InstallMount%", "High Efficiency Image File Codec Plugin", "HEIFImageExtension"
call :RemoveWindowsComponent "%InstallMount%", "Maps App", "Maps"
call :RemoveWindowsComponent "%InstallMount%", "Messaging App", "Messaging"
call :RemoveWindowsComponent "%InstallMount%", "Mixed Reality Portal App", "MixedRealityPortal"
call :RemoveWindowsComponent "%InstallMount%", "My Office App", "OfficeHub"
call :RemoveWindowsComponent "%InstallMount%", "OneNote App", "OfficeOneNote"
call :RemoveWindowsComponent "%InstallMount%", "Mobile Plans App", "OneConnect"
call :RemoveWindowsComponent "%InstallMount%", "Paint 3D App", "Paint3D"
call :RemoveWindowsComponent "%InstallMount%", "People App", "People"
call :RemoveWindowsComponent "%InstallMount%", "Photos App", "Photos"
call :RemoveWindowsComponent "%InstallMount%", "Print 3D App", "Print3D"
call :RemoveWindowsComponent "%InstallMount%", "Screen Sketch App", "ScreenSketch"
call :RemoveWindowsComponent "%InstallMount%", "Skype App", "SkypeApp"
call :RemoveWindowsComponent "%InstallMount%", "Solitaire Collection App", "SolitaireCollection"
call :RemoveWindowsComponent "%InstallMount%", "Voice Recorder App", "SoundRecorder"
call :RemoveWindowsComponent "%InstallMount%", "Sticky Notes App", "StickyNotes"
call :RemoveWindowsComponent "%InstallMount%", "Google's VP9 WebM Video Codec Plugin", "VP9VideoExtensions"
call :RemoveWindowsComponent "%InstallMount%", "Microsoft Pay App", "WalletService"
call :RemoveWindowsComponent "%InstallMount%", "Web Media Extension Plugin", "WebMediaExtensions"
call :RemoveWindowsComponent "%InstallMount%", "Webp Image Extension Plugin", "WebpImageExtensions"
@REM call :RemoveWindowsComponent "%InstallMount%", "Windows Store App", "WindowsStore"
call :RemoveWindowsComponent "%InstallMount%", "Xbox App", "XboxApp"
call :RemoveWindowsComponent "%InstallMount%", "Xbox Identity Provider", "XboxIdentityProvider"
call :RemoveWindowsComponent "%InstallMount%", "Your Phone App", "YourPhone"
call :RemoveWindowsComponent "%InstallMount%", "Groove Music App", "ZuneMusic"
call :RemoveWindowsComponent "%InstallMount%", "Films and TV App", "ZuneVideo"
call :RemoveWindowsComponent "%InstallMount%", "Movies and TV App", "ZuneVideo"
